version: "3.9"

services:
  devopsdb:
    image: saibannu/database:v1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  application:
    image: saibannu/javaapp:v1
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
